import { BaseLayout } from "@/components/layouts/base-layout";
import { isValidLocale } from "@/utils/internalization";
import type { Metadata } from "next";
import {setRequestLocale} from 'next-intl/server';
import { notFound } from "next/navigation";

export const metadata: Metadata = {
	title: "Taletix - Freelancer Platform",
	description: "Generated by create next app",
};

const LocaleLayout: React.FC<
	Readonly<{
		children: React.ReactNode;
		params: Promise<{ locale: string }>;
	}>
> = async ({ children, params }) => {
	const { locale } = await params;

	if (!isValidLocale(locale)) {
		notFound();
	}

	setRequestLocale(locale)
	return <BaseLayout locale={locale}>{children}</BaseLayout>;
};

export default LocaleLayout;
